/* Generated By:JavaCC: Do not edit this line. InterpreterExcelConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface InterpreterExcelConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 5;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 6;
  /** RegularExpression Id. */
  int STRING_LITERAL = 7;
  /** RegularExpression Id. */
  int TIMESTAMP_LITERAL = 8;
  /** RegularExpression Id. */
  int VARIABLE = 9;
  /** RegularExpression Id. */
  int FORMATTED = 10;
  /** RegularExpression Id. */
  int FOR = 11;
  /** RegularExpression Id. */
  int FROM = 12;
  /** RegularExpression Id. */
  int TO = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int END = 15;
  /** RegularExpression Id. */
  int ASSIGNMENT_OPERATOR = 16;
  /** RegularExpression Id. */
  int STRING_CONCATENATION_OPERATOR = 17;
  /** RegularExpression Id. */
  int COMPARISON_OPERATOR = 18;
  /** RegularExpression Id. */
  int CELL_REFERENCE = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<STRING_LITERAL>",
    "<TIMESTAMP_LITERAL>",
    "<VARIABLE>",
    "\"FORMATTED\"",
    "\"for\"",
    "\"from\"",
    "\"to\"",
    "\"do\"",
    "\"end\"",
    "\"=\"",
    "\"&\"",
    "<COMPARISON_OPERATOR>",
    "<CELL_REFERENCE>",
  };

}
